name: Auto Update

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  update:
    name: Update&Push
    runs-on: alt-sisyphus

    steps:
      - name: Install libs on container
        run: |
          apt-get update
          apt-get install -y git python3 "python3(requests)"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          token: ${{ secrets.TOKEN }}

      - name: Setup git
        run: |
          git config --global user.name "Automatic Updater"
          git config --global user.email "ci@altlinux.space"
          git config --global --add safe.directory '*'

      - name: Setup
        run: sh auto-update/update.sh
