name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  lint-vala:
    name: Lint vala files
    runs-on: alt-sisyphus
    container:
      image: altlinux.space/alt-gnome/coding-style-image:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint files
        uses: alt-gnome/coding-style-actions/vala@main

  checkers:
    name: Run checkers
    runs-on: alt-sisyphus

    steps:
      - name: Update apt cache
        run: apt-get -y update

      - name: Install git and python
        run: apt-get install -y git python3

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Run indentation checker
        run: python3 vala-checkers/indentation_checker.py .

      - name: Run empty lines checker
        run: python3 vala-checkers/empty_lines_checker.py .

  # test-build:
  #   name: Test Build
  #   runs-on: alt-sisyphus
  #   container:
  #     image: altlinux.space/rirusha/riru-build-image:latest

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Gear
  #       run: |
  #         rbu to-gear

  #     - uses: actions/build-rpm-action@main
  #       name: Build RPMs
